version: '3.2'

services:
  interop-db:
    image: postgres
    environment:
     POSTGRES_USER: "postgres"
     POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./volumes/var/lib/postgresql/data:/var/lib/postgresql/data
  interop-server:
    build:
      context: ../
      dockerfile: server/Dockerfile
      cache_from:
        - auvsisuas/interop-server:latest
    image: auvsisuas/interop-server
    environment:
     POSTGRES_USER: "postgres"
     POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./volumes/mount:/mount
      - ./volumes/logs/uwsgi:/var/log/uwsgi
      - ./volumes/var/www/media/objects:/var/www/media/objects
    ports:
      - "8000:80"
    depends_on:
      - interop-db
